# ~/.ssh/config.d/github-personal.conf  (stowed)
#
# This is a basic, pluggable ssh config for using a personal github account on a work machine
# Its setup for 1password-stored SSH keys, allowing a separation between work and personal git usage
#
# To include this in your main ssh config at ~/.ssh/config, use
#   Include ~/.ssh/config.d/*.conf
# Make sure you ran `stow` before and the symlink is correct
#
# If you haven't already, create a space-free symlink for the 1Password SSH agent:
#   mkdir -p ~/.1password && \
#   ln -s ~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock ~/.1password/agent.sock
#
# Switch a repo to use this host alias (copy/paste in the repo):
#   git remote set-url origin git@github-personal:<YOUR_GH_USER>/<REPO>.git
# 
# e.g git remote set-url origin git@github-personal:scyhhe/dotfiles.git 
#
# Quick tests:
#   ssh -T github-personal
#   git ls-remote git@github-personal:<YOUR_GH_USER>/<REPO>.git

Host github-personal
  HostName github.com
  User git
  IdentitiesOnly no
  IdentityAgent ~/.1password/agent.sock
  IdentityFile none
